---
Sample Report Query: !ruby/hash-with-ivars:Report
  ivars:
    :@report_name: Sample Report Query
    :@acquired_order: ''
    :@acquired_filter: ''
    :@added_order: '6'
    :@added_filter: ''
    :@base_size_order: ''
    :@base_size_filter: ''
    :@category_order: ''
    :@category_filter: ''
    :@completed_order: ''
    :@completed_filter: ''
    :@cost_order: ''
    :@cost_filter: ''
    :@description_order: '4'
    :@description_filter: fun
    :@genre_filter: ''
    :@genre_order: '5'
    :@icon_image_order: '2'
    :@icon_image_filter: ''
    :@id_order: '1'
    :@id_filter: ''
    :@image_dir_order: ''
    :@image_dir_filter: ''
    :@item_image_order: '7'
    :@item_image_filter: ''
    :@location_order: ''
    :@location_filter: ''
    :@manufacturer_order: ''
    :@manufacturer_filter: ''
    :@material_order: ''
    :@material_filter: ''
    :@name_order: '3'
    :@name_filter: ''
    :@notes_order: ''
    :@notes_filter: ''
    :@number_bases_order: ''
    :@number_bases_filter: ''
    :@painter_order: ''
    :@painter_filter: ''
    :@quantity_order: ''
    :@quantity_filter: ''
    :@rule_system_order: ''
    :@rule_system_filter: ''
    :@scale_order: ''
    :@scale_filter: ''
    :@status_order: ''
    :@status_filter: ''
    :@tags_order: ''
    :@tags_filter: ''
    :@type_order: ''
    :@type_filter: ''
    :@value_order: ''
    :@value_filter: ''
    :@web_order: ''
    :@web_filter: ''
    :@query_name: Sample Report Query
    :@acquired_exact: ''
    :@acquired_sort: ''
    :@added_exact: ''
    :@added_sort: ''
    :@base_size_exact: ''
    :@base_size_sort: ''
    :@category_exact: ''
    :@category_sort: ''
    :@completed_exact: ''
    :@completed_sort: ''
    :@cost_exact: ''
    :@cost_sort: ''
    :@description_exact: ''
    :@description_sort: ''
    :@genre_sort: ''
    :@genre_exact: ''
    :@icon_image_exact: ''
    :@icon_image_sort: ''
    :@id_exact: ''
    :@id_sort: ''
    :@image_dir_exact: ''
    :@image_dir_sort: ''
    :@item_image_exact: ''
    :@item_image_sort: ''
    :@location_exact: ''
    :@location_sort: ''
    :@manufacturer_exact: ''
    :@manufacturer_sort: ''
    :@material_exact: ''
    :@material_sort: ''
    :@name_exact: ''
    :@name_sort: ''
    :@notes_exact: ''
    :@notes_sort: ''
    :@number_bases_exact: ''
    :@number_bases_sort: ''
    :@painter_exact: ''
    :@painter_sort: ''
    :@quantity_exact: ''
    :@quantity_sort: ''
    :@rule_system_exact: ''
    :@rule_system_sort: ''
    :@scale_exact: ''
    :@scale_sort: ''
    :@status_exact: ''
    :@status_sort: ''
    :@tags_exact: ''
    :@tags_sort: ''
    :@type_exact: ''
    :@type_sort: ''
    :@value_exact: ''
    :@value_sort: ''
    :@web_exact: ''
    :@web_sort: ''
    :@report_format: ''
    :@exclude_html_format: ''
    :@exclude_summary: ''
  elements: {}
